# Generated by Django 5.1.6 on 2025-02-16 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(max_length=20, unique=True)),
                ('open_date', models.DateField(blank=True, null=True)),
                ('plaintiff', models.CharField(blank=True, max_length=100, null=True)),
                ('defendant', models.CharField(blank=True, max_length=100, null=True)),
                ('procurator', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(auto_now_add=True)),
                ('last_update', models.DateTimeField()),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files_consultant.process')),
            ],
        ),
    ]
