# Generated by Django 5.1.6 on 2025-06-19 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_consultant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='defendant',
            field=models.CharField(blank=True, help_text='Nombre del demandado del proceso', max_length=300, null=True, verbose_name='Demandado'),
        ),
        migrations.AlterField(
            model_name='process',
            name='file_number',
            field=models.CharField(help_text='Número de radicado del proceso', max_length=100, unique=True, verbose_name='Radicado'),
        ),
        migrations.AlterField(
            model_name='process',
            name='open_date',
            field=models.DateField(blank=True, help_text='Fecha en que se abrió el proceso', null=True, verbose_name='Fecha de apertura'),
        ),
        migrations.AlterField(
            model_name='process',
            name='plaintiff',
            field=models.CharField(blank=True, help_text='Nombre del demandante del proceso', max_length=300, null=True, verbose_name='Demandante'),
        ),
        migrations.AlterField(
            model_name='process',
            name='procurator',
            field=models.CharField(blank=True, help_text='Nombre del procurador del proceso', max_length=300, null=True, verbose_name='Procurador'),
        ),
        migrations.AlterField(
            model_name='processsnapshot',
            name='last_update',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del proceso', verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='processsnapshot',
            name='process',
            field=models.ForeignKey(help_text='Proceso relacionado', on_delete=django.db.models.deletion.CASCADE, to='files_consultant.process', verbose_name='Proceso'),
        ),
        migrations.AlterField(
            model_name='processsnapshot',
            name='snapshot_date',
            field=models.DateField(auto_now_add=True, help_text='Fecha en que se tomó la captura del proceso', verbose_name='Fecha de captura'),
        ),
    ]
