services:
  web:
    build: .
    container_name: webscraper
    command: daphne -p 8000 -b 0.0.0.0 consulta_radicados.asgi:application
    volumes:
      - .:/home/app
    working_dir: /home/app/webscraper
    ports:
      - "8010:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - consulta_radicados_network

  db:
    image: postgres:17
    container_name: webscraper_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5440:5432"
    networks:
      - consulta_radicados_network

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - '80:80'
    depends_on:
      - web
    volumes:
      - ./nginx:/etc/nginx/conf.d # Nginx configuration
      - ./static:/home/app/static # Static files
      - ./media:/home/app/media # Media files
    networks:
      - consulta_radicados_network

networks:
  consulta_radicados_network:
    driver: bridge

volumes:
  postgres_data:
